### PR TITLE
Fix serialization

### PR DESCRIPTION
**Pull request by SanjoDeundiak**

### CODE REVIEW

**Comment by SanjoDeundiak** [comment]
@mikelodder7 could you please checkout 294da332a5e30bfadbcea5a8dd024d0e33ccc4cd and confirm that tests I added do not pass with current serde implementation, and then checkout my fix f27694e7a829fb8bdd69c8851ed04974e6cf60a0 and confirm that tests pass.
BTW I rebased the PR

**Comment by mikelodder7** [comment]
Will do

**Comment by mikelodder7** [comment]
Thanks for raising the issue. I believe this [7ebb26e](https://github.com/mikelodder7/bls12_381_plus/commit/7ebb26e9ea84644da0cef7aedbe73b2770870ca0) fixes this better.

**Comment by mikelodder7** [comment]
Fixed

**Pull request closed without merging**
